### ISSUE TITLE
Help with adding dashboard

### ISSUE THREAD

**Issue by NessK** [njobrien1006/hass_traeger#74]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/njobrien1006/hass_traeger/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi, due to lack of knowledge I am unable to add the dashboard from this repository to my Home assistant installation. 
I have used the integration for a while and really enjoying it, fantastic work! Much appreciated!
I have tried to search the web to my best abilities when it comes to addint the dashboard but im unable to make it work.

### Describe the solution you'd like

Some guidance or update on the readme on how to add the dashboard? Im sure this will help many other than me

### Describe alternatives you've considered

google, I have tried to add the repository in HACS as lovelace, but unable to install this way.

### Additional context

 Again, thanks for your excellent work!
My apologies if I did this the incorrect way, this is my first time reporting a issue on github.

**Comment by njobrien1006** [comment]
It sounds as though you have successfully been able to add the integration VIA custom components or HACS but are just struggling adding to the LoveLace UI? Can you add anything to the dashboard? If not, see [HA-Onboarding](https://www.home-assistant.io/getting-started/onboarding_dashboard/).

If you are having issues laying out your dashboard to display everything in a single screen, this a JSON example of mine [here](njobrien1006/hass_traeger/config/.storage/lovelace). However, this setup caters to CodeSpaces. In order to paste into your UI it would need to be [JSON -> YAML converted](https://www.bairesdev.com/tools/json2yaml/). Additionally, there are 2 other dependencies in my config that are detailed [here](https://github.com/njobrien1006/hass_traeger/blob/c07d4559c213254f580a31bd4f023106de7201d5/config/.storage/lovelace_resources#L7-L17), [here](https://github.com/njobrien1006/hass_traeger/blob/c07d4559c213254f580a31bd4f023106de7201d5/scripts/develop#L19), and [here](config/www/epoch-clock-card/epoch-clock-card.js).

**Comment by NessK** [comment]
Thanks for your response!
Yes the integration is added through HACS, and working great!
I have made my own dashboard for my BBQ's which works fine, only with graph of temperatures in a few statuses. But Im jealous of the fancy dashboard in you example! :)
I will read through your post a few more times and try to understand it over a few evening! 

Thanks again for your answer, and for your excellent effort on this integration!

**Comment by NessK** [comment]
Successfully added the lovelace with you guidance. Thank you so much!
